services:
  - type: worker
    name: ecos-de-eldoria-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CHANNEL_SOLITARIO
        sync: false
      - key: CHANNEL_GRUPO
        sync: false
      - key: CHANNEL_TABLON
        sync: false
      - key: CHANNEL_LOGROS
        sync: false
      - key: CHANNEL_COMANDOS
        sync: false
      - key: CHANNEL_DADOS
        sync: false
